name: Watchdog
permissions:
  contents: write
on:
  schedule:
    - cron: */5 * * * *
  workflow_dispatch:


jobs:
  wakucanary:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run wakucanary
      id: wakucanary
      run: |
        ./scripts/run.sh
